name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write  # Needed for creating releases
  packages: write  # Needed for npm publishing (if using GitHub Packages)

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run unit tests
      run: npm run test:run
    
    - name: Build project
      run: npm run build

  publish:
    needs: test-and-build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Verify package contents
      run: |
        echo "📦 Package contents:"
        npm pack --dry-run
    
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Extract tag name
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: Release ${{ steps.tag.outputs.tag }}
        body: |
          🚀 **CubicAgentKit ${{ steps.tag.outputs.tag }}**
          
          This release has been automatically published to npm after passing all tests.
          
          ## Installation
          ```bash
          npm install @cubicler/cubicagentkit@${{ steps.tag.outputs.tag }}
          ```
          
          ## Changes
          See the [commit history](https://github.com/${{ github.repository }}/commits/${{ steps.tag.outputs.tag }}) for detailed changes.
        draft: false
        prerelease: false
